### PR TITLE
Backport 1.0.13

### PR DESCRIPTION
**Pull request by kskmori**
Andrew,

I think that backporting work has almost done and now it's time to merge and start testing phase.
Please acknowledge the pull request and let's go forward for the release.

There are three open issues in my mind and they can be settled down in the testing phase.
- https://github.com/kskmori/pacemaker-1.0/issues/3
- https://github.com/kskmori/pacemaker-1.0/issues/8
- https://github.com/kskmori/pacemaker-1.0/issues/11

I've also started running CTS over here with
- heartbeat-3.0.5
- corosync-1.4.4
- cluster-glue-1.0.10
  on RHEL5/6.

Regards,

### CODE REVIEW

**Comment by beekhof** [comment]
On Wed, Aug 22, 2012 at 8:56 PM, Keisuke MORI notifications@github.comwrote:

> Andrew,
> 
> I think that backporting work has almost done and now it's time to merge
> and start testing phase.
> Please acknowledge the pull request and let's go forward for the release.
> 
> There are three open issues in my mind and they can be settled down in the
> testing phase.
> - https://github.com/kskmori/pacemaker-1.0/issues/3
> - https://github.com/kskmori/pacemaker-1.0/issues/8
> 
> How strongly do you feel about these two bugs?
> Neither are regressions, so I would be inclined to go ahead with the
> release and fix them when the opportunity arises.
> Thoughts?

How is CTS going for you?

**Comment by kskmori** [comment]
> - https://github.com/kskmori/pacemaker-1.0/issues/3

From our team's point of view, we consider that this is an important issue particularly when we are using stateful resources (such as pgsql replications) because it may lead a data corruption. We have been happily using group resources and it blocks in such situations as we expected, but we encountered this issue when we want to use a stateful resource solely. I will look into again if we can workaround this without fixing it but still we are glad if it would be fixed very soon.

If you really think that it is difficult to fix soon then we might have to postpone fixing it.
I don't think I can do what you can not do :).

> - https://github.com/kskmori/pacemaker-1.0/issues/3

I think we can skip this for 1.0.13.  I don't think this is an urgent issue.

As for CTS, Nozawa-san, my colleague, is running it and he said that it observed that several badnews. We are going to look into the details. He said that some of them was observed in the previous release (1.0.12) too but some of them looks new.

**Comment by beekhof** [comment]
Just to check, is it issue 8 or 3 that is critical to you?
Both urls are for issue 3 :-)

In any case, I will merge this now.  We can merge additional backports as necessary.

**Comment by kskmori** [comment]
Oops, I meant issue 3 is important and issue 8 is not so important for me. Sorry about that.

Anyway, I discussed with my colleagues about issue 3, and we think that we can stand this as a known limitation for the present.

**Comment by beekhof** [comment]
Ok. I'm trying to finish up 1.1.8, once that is done I will attempt to fix issue 3 (and possibly 8) and then we can release 1.0.13.
Does that sound ok?

**Comment by kskmori** [comment]
Sounds great. I hope that 1.1.8 would be released very soon too:)

**Pull request merged**
